name: API Tests

on: [push, pull_request]

jobs:
  dev-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Set up Java for Allure
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Run Docker container
        run: docker run -d -p 3000:3000 ghcr.io/danielsilva-loanpro/sdet-interview-challenge:latest

      - name: Run DEV tests
        run: npm test -- tests/dev.users.spec.ts

      - name: Generate BUGS.md
        if: always()
        run: npm run bugs

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-dev
          path: coverage/

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-dev
          path: reports/

      - name: Generate Allure HTML report
        if: always()
        run: npm run allure:report

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-dev
          path: allure-results/

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-dev
          path: allure-report/

      - name: Upload BUGS markdown
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bugs-dev
          path: BUGS.md

  prod-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Set up Java for Allure
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Run Docker container
        run: docker run -d -p 3000:3000 ghcr.io/danielsilva-loanpro/sdet-interview-challenge:latest

      - name: Run PROD tests
        run: npm test -- tests/prod.users.spec.ts

      - name: Generate BUGS.md
        if: always()
        run: npm run bugs

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-prod
          path: coverage/

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-prod
          path: reports/

      - name: Generate Allure HTML report
        if: always()
        run: npm run allure:report

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-prod
          path: allure-results/

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-prod
          path: allure-report/

      - name: Upload BUGS markdown
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bugs-prod
          path: BUGS.md
